export const FETCH_CITY_START = 'FETCH_CITY_START';
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';
export const FETCH_CITY_FAILED = 'FETCH_CITY_FAILED';
export const NEXT_CITY = 'NEXT_CITY';
export const PREVIOUS_CITY = 'PREVIOUS_CITY';
